DROP TABLE IF EXISTS VEHICLES;
DROP TABLE IF EXISTS LOADS;
DROP TABLE IF EXISTS DRIVERS;

CREATE TABLE VEHICLES (
                REGISTRATION_NUMBER VARCHAR NOT NULL,
                CAPACITY INTEGER NOT NULL,
                STATUS VARCHAR NOT NULL,
                CURRENT_CITY VARCHAR NOT NULL,
                CONSTRAINT vehicles_pk PRIMARY KEY (REGISTRATION_NUMBER)
);


CREATE SEQUENCE loads_id_seq;

CREATE TABLE LOADS (
                ID BIGINT NOT NULL DEFAULT nextval('loads_id_seq'),
                REGISTRATION_NUMBER VARCHAR NOT NULL,
                STATUS VARCHAR NOT NULL,
                WEIGHT INTEGER NOT NULL,
                CONSTRAINT loads_pk PRIMARY KEY (ID)
);


ALTER SEQUENCE loads_id_seq OWNED BY LOADS.ID;

CREATE TABLE DRIVERS (
                DRIVING_LICENSE_NUM VARCHAR(7) NOT NULL,
                REGISTRATION_NUMBER VARCHAR NOT NULL,
                FIRST_NAME VARCHAR NOT NULL,
                SECOND_NAME VARCHAR NOT NULL,
                LICENSE_END_DATE DATE NOT NULL,
                STATUS VARCHAR NOT NULL,
                CURRENT_CITY VARCHAR NOT NULL,
                CONSTRAINT drivers_pk PRIMARY KEY (DRIVING_LICENSE_NUM)
);


ALTER TABLE DRIVERS ADD CONSTRAINT vehicle_drivers_fk
FOREIGN KEY (REGISTRATION_NUMBER)
REFERENCES VEHICLES (REGISTRATION_NUMBER)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE LOADS ADD CONSTRAINT vehicle_loads_fk
FOREIGN KEY (REGISTRATION_NUMBER)
REFERENCES VEHICLES (REGISTRATION_NUMBER)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
