DROP TABLE IF EXISTS LOADS;
DROP TABLE IF EXISTS DTRIVERS;
DROP TABLE IF EXISTS VEHICLES;
DROP TABLE IF EXISTS LOCATIONS;

CREATE SEQUENCE locations_id_seq;

CREATE TABLE LOCATIONS (
                ID BIGINT NOT NULL DEFAULT nextval('locations_id_seq'),
                NAME VARCHAR NOT NULL,
                LATITUDE DOUBLE PRECISION NOT NULL,
                LONGITUDE DOUBLE PRECISION NOT NULL,
                CONSTRAINT locations_pk PRIMARY KEY (ID)
);


ALTER SEQUENCE locations_id_seq OWNED BY LOCATIONS.ID;

CREATE SEQUENCE vehicles_id_seq;

CREATE TABLE VEHICLES (
                ID BIGINT NOT NULL DEFAULT nextval('vehicles_id_seq'),
                LOCATION_ID BIGINT NOT NULL,
                REGISTRATION_NUMBER VARCHAR NOT NULL,
                CAPACITY INTEGER NOT NULL,
                CURRENT_CITY VARCHAR NOT NULL,
                CONSTRAINT vehicles_pk PRIMARY KEY (ID)
);


ALTER SEQUENCE vehicles_id_seq OWNED BY VEHICLES.ID;

CREATE TABLE LOADS (
                ID BIGINT NOT NULL,
                LOCATION_ID BIGINT NOT NULL,
                VEHICLE_ID BIGINT NOT NULL,
                STATUS VARCHAR NOT NULL,
                WEIGHT INTEGER NOT NULL,
                CONSTRAINT loads_pk PRIMARY KEY (ID)
);


CREATE TABLE DRIVERS (
                ID BIGINT NOT NULL,
                VEHICLE_ID BIGINT NOT NULL,
                DRIVING_LICENSE_NUM VARCHAR(7) NOT NULL,
                FIRST_NAME VARCHAR NOT NULL,
                LAST_NAME VARCHAR NOT NULL,
                LICENSE_END_DATE DATE NOT NULL,
                STATUS VARCHAR NOT NULL,
                CURRENT_CITY VARCHAR NOT NULL,
                CONSTRAINT drivers_pk PRIMARY KEY (ID)
);


ALTER TABLE VEHICLES ADD CONSTRAINT locations_vehicles_fk
FOREIGN KEY (LOCATION_ID)
REFERENCES LOCATIONS (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE LOADS ADD CONSTRAINT locations_loads_fk
FOREIGN KEY (LOCATION_ID)
REFERENCES LOCATIONS (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE DRIVERS ADD CONSTRAINT vehicles_drivers_fk
FOREIGN KEY (VEHICLE_ID)
REFERENCES VEHICLES (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE LOADS ADD CONSTRAINT vehicles_loads_fk
FOREIGN KEY (VEHICLE_ID)
REFERENCES VEHICLES (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
